### ISSUE TITLE
New studies 

### ISSUE THREAD

**Issue by salehalobaidi** [mandhri/hcymeth#4]
## Armstrong et al. 2018
* 10.3389/fgene.2018.00358
* multicentre, double-blind, randomized, and controlled clinical trial
* Illumina Infinium HumanMethylation450K BeadChip microarray
* Statistical analyses were performed using KING software
* 180 participants 
* 104 European descent and 76 of African descent from Vitamin Intervention for Stroke Prevention (VISP) clinical trial.
*	NCBIgeo data not available 

## Kinoshita et al. 2013
*	http://dx.doi.org/10.4161/epi.24621
*	Genome-wide DNA methylation profiling study 
*	Plasma total Hcy levels were measured by high performance liquid chromatograph.
*	Infinium HumanMethylation450 BeadChips
*	Statistical analysis ??
*	42 patients 
*	Male patients diagnosed with schizophrenia were recruited from Tokushima and Kochi University Hospitals in Japan. 
*	NCBIgeo data not available 

## Fiorito et al. 2013
•	http://dx.doi.org/10.1016/j.numecd.2013.10.026
•	prospective case-control study
•	Illumina-HumanMethylation450K-BeadChip
•	Statistical analysis??
•	412 participants 
•	206 myocardial infarction (MI) cases and 206 matched controls from EPIC cohort 
•	NCBIgeo data availability?

## Sae-Lee et al. 2020
•	10.1371/journal.pone.0234578
•	Targeted DNA methylation analysis
•	Illumina Infinium 450K
•	IBM SPSS statistical software 
•	72 participants 
•	28 T2D patients from (IDCD) study and 44 individuals from B-PROOF study
•      (GSE62003) / (GSE74548)

## van Wijngaarden et al. 2011
•	10.1186/1471-2318-11-80
•	Randomized double-blind placebo-controlled trial
•	Illumina Omni-express array
•	Statistical analysis?
•	2919 subjects 
•	Dutch Men and women, aged 65 years and older were recruited 
•	NCBIgeo data not available 

## James et al. 2018
•	10.1093/cdn/nzy082
•	Prospective case study 
•	Illumina Infinium HumanMethytlation450 array
•	Stata 14.0 (Stata Corporation)
•	120 participants 
•	From (MDEG) study and (ENID) Trial, both conducted in the rural West Kiang region of Gambia.
•	GSE59592

## de la Rocha et al. 2016
* 10.1038/srep25867
* Retrospective cohort study 
* Illumina Infinium HumanMethylation450 BeadChip
* STATISTICA software (StatSoft)
* 20 samples 
* 4 from the LI cohort and 16 from AMM group, state of Guanajuato, in central Mexico.

**Comment by mandhri** [comment]
thanks for 6 updates
